### ISSUE TITLE
Sync with head?

### ISSUE THREAD

**Issue by slimshader** [DerelictOrg/DerelictBgfx#9]
Hey,

I am trying those bindings with bgfx head and I am getting run-time errors on bgfx_init(). From the brief look it seems that it is because of recently added Vulcan support tand now BGFX_RENDERER_TYPE_COUNT points to Vulcan as default backend. Any chance of updating the bindings to more recent gbfx version?

**Comment by p0nce** [comment]
Sorry, I'm very busy, won't be able to maintain much, especially this one about bgfx which constantly changes. Any pull request appreciated.

**Comment by slimshader** [comment]
How do you prepare bindings? With automated tools or by hand?

**Comment by p0nce** [comment]
By hand. The easiest way is to diff relevant bgfx headers from the version that the last commit references, with the current bgfx headers. That way you don't forget anything.

**Comment by p0nce** [comment]
Done thanks to @olehlong
